const HTTP_STATUS_CODES = {
    "FETCH": 200,
    "CREATED": 201,
    "UPDATED": 201,
    "DELETED": 201,
    "BAD_REQUEST": 400,
    "NOT_FOUND": 404,
    "INTERNAL_SERVER": 500
}

module.exports = HTTP_STATUS_CODES